spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_gorm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    name: nav_links
    username: root # ????mysql???
    password: 233233 # ????mysql??
    driver-class-name: com.mysql.cj.jdbc.Driver
    p6spy:
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"

  jackson:
#    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE

  jpa:
    #    generate-ddl: false # ??????,???????, ?????????????. (????: ??????, ???????, ??????) ?????????true,
#    hibernate:
#      ddl-auto: update # create | create-drop | update | none | validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect